name: _job_build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  proton:
    name: Build ${{ inputs.name }}
    runs-on: ubuntu-22.04
    steps:
    - name: Prepare host
      run: sudo apt update && sudo apt-get install -y ccache fontforge-nox

    - name: Restore cache
      id: ccache-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.ccache
        key: ccache-proton-${{ github.run_id }}
        restore-keys: |
          ccache-proton
          
    - name: Link
      run: |
        sudo mkdir -pv /mnt/a
        sudo ln -sfv /mnt/a a
        sudo chmod 777 -R a

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        fetch-tags: true
        submodules: false
        path: a

    - name: Patch
      working-directory: ./a
      run: |
        git submodule update --init --filter=tree:0 --recursive --depth=1
        # apply proton-ge-custom patches
        bash -x ./patches/protonprep-valve-staging.sh || true
        # strip binaries at compile time to save space in the runner
        patch -Np1 -i ./.github/patches/0001-build-strip-binaries-early.patch
        mkdir ./build

    - name: Configure
      working-directory: ./a/build
      run: |
        bash -x ../configure.sh --build-name=${{ inputs.name }} --container-engine=docker

    - name: Make ${{ inputs.name }}
      working-directory: ./a/build
      run: |
        make -j$(nproc) redist VERBOSE=0 V=0

    - name: Save cache
      id: ccache-save
      if: always()
      uses: actions/cache/save@v4
      with:
        path: ~/.ccache
        key: ${{ steps.ccache-restore.outputs.cache-primary-key }}

    - name: Upload artifact ${{ inputs.name }}.tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}.tar.gz
        path: ./a/build/${{ inputs.name }}.tar.gz

    - name: Upload artifact ${{ inputs.name }}.tar.zst
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}.tar.zst
        path: ./a/build/${{ inputs.name }}.tar.zst

    - name: Upload artifact ${{ inputs.name }}.sha512sum
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}.sha512sum
        path: ./a/build/${{ inputs.name }}.sha512sum

